---
kind: pipeline
name: default

steps:
        - name: build
          image: tooom/docker-vbox-packer
          commands:
                  - cd thehive-training
                  - packer build thehive-training_virtualbox.json
